# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d375d0f3e9407b03072c29692476bd6371e66f7044afe27793a0ebb86f7c20e6ea6a060a822ce66ad0d88c03152dbe472fb7be1414d7a6157a16a5ff23b601a

test:
  secret_key_base: c10841c800cc17d6cda1f01794405d6472ec5a9e6224159041ad91f6b192b5679f5933453989588f3b8b0bac655a155a5fffe9daef68fe077e2e3a3775960add

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
